Fix circular import in asset registration system (#124)
## Summary
Replaces module-level imports with lazy loading to break circular
dependency between asset_regisry.py, register.py and asset library
modules.


Removes module level imports from assert_registry.py and wrapped them
into a function which is only called on first access.

Fixes the following circular import : 
Minimal script to reproduce:

```
from isaaclab.app import AppLauncher
import argparse
parser = argparse.ArgumentParser(description="Keyboard teleoperation for Isaac Lab environments.")
AppLauncher.add_app_launcher_args(parser)
args_cli = parser.parse_args()
args_cli.headless = True
app_launcher_args = vars(args_cli)
app_launcher = AppLauncher(app_launcher_args)
from isaac_arena.assets.object_library import LibraryObject
```


```
Traceback (most recent call last):
  File "/workspaces/isaac_arena/isaac_arena/examples/policy_runner.py", line 24, in <module>
    from isaac_arena.assets.object_library import LibraryObject
  File "/workspaces/isaac_arena/isaac_arena/assets/object_library.py", line 19, in <module>
    from isaac_arena.assets.register import register_asset
  File "/workspaces/isaac_arena/isaac_arena/assets/register.py", line 16, in <module>
    from isaac_arena.assets.asset_registry import AssetRegistry, DeviceRegistry
  File "/workspaces/isaac_arena/isaac_arena/assets/asset_registry.py", line 118, in <module>
    from isaac_arena.assets.background_library import *  # noqa: F403, F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/isaac_arena/isaac_arena/assets/background_library.py", line 16, in <module>
    from isaac_arena.assets.register import register_asset
ImportError: cannot import name 'register_asset' from partially initialized module 'isaac_arena.assets.register' (most likely due to a circular import) (/workspaces/isaac_arena/isaac_arena/assets/register.py)

```

---------

Co-authored-by: Vikram Ramasamy <158473438+viiik-inside@users.noreply.github.com>